
services:
  api:
    build: 
      context: ./cepal-tdp
      args:
        - RUN_MAKE=false
        #- RUN_MAKE=false
    container_name: cepal-api
    ports:
      - "5000:5000"
    volumes:
      - datos_compartidos:/app/data # La primera vez que se monta un volumen, 
                                    # se copia el contenido de la imagen al volumen

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: appdb
    volumes:
      - postgres_data:/var/lib/postgresql/data

  
  dash:
    build: ./cepal-dashboard
    container_name: cepal-dash
    ports:
      - "5001:5001"
    volumes:
      - datos_compartidos:/app/data:ro # Aqui se pisa lo que hubiera en la imagen
    environment:
      API_BASE_URL: http://api:5000
    depends_on:
      - api
      - db

volumes:
  datos_compartidos: # Aca se almacena el resultado del make en el contenedor api
  postgres_data:
